sudo: false

language: node_js

node_js:
  - "stable"

notifications:
  email: false
  
cache:
  directories:
    - "node_modules"

services:
  - postgresql

  
env:
  global:
  - NODE_ENV=test

before_script:
  - psql -c 'create database teamwork_test_db;' -U postgres
  - npm run build

script:
  - npm test

after_success:
 - npm run coverage
 