sudo: false

language: node_js

node_js:
  - "stable"

notifications:
  email: false

addons:
  postgresql: '12'
  
cache:
  directories:
    - "node_modules"

services:
  - postgresql

env:
  global:
  - NODE_ENV=test

before_script:
  - travis_wait 30 npm install
  - psql -c 'create database teamworktest;' -U postgres
  - travis_wait npm install
  - node ./src/models/db.js createAllTables
  - travis_wait 30 node ./src/models/data.js insertAllData
  - npm run build

script:
  - npm test

after_success:
  - npm run coverage