sudo: false

language: node_js

node_js:
  - "stable"

notifications:
  email: false
  
cache:
  directories:
    - "node_modules"

install:
  - npm install

services:
  - postgresql

env:
  global:
  - NODE_ENV=test

before_script:
  - psql -c 'create database teamwork;' -U postgres
  - psql -U postgres -f ./src/models/init.sql -d teamwork 
  - npm run build

script:
  - npm test
after_success:
  - npm run coverage