sudo: false

language: node_js

node_js:
  - "stable"

services:
  - postgresql

addons:
  postgresql: "12"

notifications:
  email: false

install:
  - npm install

before_script:
  - psql -c 'create database teamwork;' -U postgres

script:
   - npm run coverage

after_success:
  - npm run coveralls

